# Generated by Django 6.0.1 on 2026-01-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=165)),
            ],
        ),
        migrations.CreateModel(
            name='MockSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mocks.mock')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('mock', 'section')},
            },
        ),
    ]
