# Generated by Django 6.0.1 on 2026-01-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningtest',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('part', models.PositiveSmallIntegerField(default=1)),
                ('qtype', models.CharField(choices=[('mcq_single', 'Multiple choice (single)'), ('mcq_multi', 'Multiple choice (multiple)'), ('tfng', 'True/False/Not Given'), ('short', 'Short answer / Gap fill'), ('matching', 'Matching (e.g. A–E)'), ('map', 'Map/Plan/Diagram label')], max_length=20)),
                ('prompt', models.TextField()),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='listening.listeningtest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ListeningOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8)),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='listening.listeningquestion')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('question', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ListeningAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_answers', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='listening.listeningquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
