# Generated by Django 6.0.1 on 2026-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0002_listeningtest_duration_seconds_listeningquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Map/Plan/Diagram uchun rasm (ixtiyoriy).', null=True, upload_to='listening_images/'),
        ),
    ]
