# Generated by Django 6.0.1 on 2026-01-20 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0003_listeningquestion_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningquestion',
            name='image',
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='qtype',
            field=models.CharField(choices=[('short', 'Short answer / Gap fill'), ('tfng', 'True/False/Not Given'), ('mcq_single', 'Multiple choice (single)'), ('mcq_multi', 'Multiple choice (multiple)'), ('matching', 'Matching (A–E)'), ('map', 'Map/Plan label')], max_length=20),
        ),
        migrations.CreateModel(
            name='ListeningQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('group_type', models.CharField(choices=[('none', 'None'), ('notes', 'Notes/Form/Flow-chart (Gap-fill)'), ('tfng', 'True/False/Not Given block'), ('table', 'Table'), ('map', 'Map/Plan/Diagram'), ('matching', 'Matching block'), ('mcq', 'MCQ block')], default='none', max_length=20)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listening_images/')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='listening.listeningtest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test', 'order')},
            },
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Agar savol block ichida bo'lsa, shu yerda group tanlang.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='listening.listeningquestiongroup'),
        ),
        migrations.DeleteModel(
            name='ListeningAttemptAnswer',
        ),
    ]
