# Generated by Django 6.0.1 on 2026-01-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('listening', '0004_remove_listeningquestion_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_answers', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='listening.listeningquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
