# Generated by Django 6.0.1 on 2026-01-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('section', models.OneToOneField(limit_choices_to={'section': 'writing'}, on_delete=django.db.models.deletion.CASCADE, related_name='writing_test', to='mocks.mocksection')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('min_words', models.PositiveIntegerField(default=150)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='writing.writingtest')),
            ],
            options={
                'ordering': ['task_number'],
                'unique_together': {('test', 'task_number')},
            },
        ),
    ]
