# Generated by Django 6.0.1 on 2026-01-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Passage text (you can store HTML here)')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reading.readingtest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('group_type', models.CharField(choices=[('none', 'None'), ('tfng', 'True/False/Not Given'), ('mcq', 'Multiple choice'), ('mcq_multi', 'Multiple choice (multiple)'), ('short', 'Short answer / Gap fill'), ('headings', 'Matching headings'), ('matching', 'Matching (A–E / names / statements)'), ('summary', 'Summary completion')], default='none', max_length=20)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='reading.readingpassage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('passage', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('passage_order', models.PositiveSmallIntegerField(default=1)),
                ('qtype', models.CharField(choices=[('tfng', 'True/False/Not Given'), ('yesno', 'Yes/No/Not Given'), ('mcq_single', 'MCQ (single)'), ('mcq_multi', 'MCQ (multiple)'), ('short', 'Short answer / Gap fill'), ('heading', 'Heading match (choose i-x)'), ('matching', 'Matching (choose A-E / names / statements)')], max_length=20)),
                ('prompt', models.TextField()),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingpassage')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingtest')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='reading.readingquestiongroup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ReadingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reading.readingquestion')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('question', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ReadingAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_answers', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='reading.readingquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
