# Generated by Django 6.0.1 on 2026-01-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('section', models.OneToOneField(limit_choices_to={'section': 'speaking'}, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_test', to='mocks.mocksection')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveSmallIntegerField()),
                ('prompt', models.TextField()),
                ('time_limit_seconds', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='speaking.speakingtest')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
    ]
