# Generated by Django 6.0.1 on 2026-01-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('terminated', 'Terminated')], default='in_progress', max_length=20)),
                ('current_section', models.CharField(default='listening', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='mocks.mock')),
            ],
        ),
    ]
